title: Benjamin D. Adams # your name (or website title) here
logo: "/images/51419879_00201_0236_Medium.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  B.S. Computer Science from Missouri S&T. 
  <br><br>
  I'm a recent computer science graduate with a passion for autonomous robotics, search and rescue, and wildlands firefighting. I am very interested in autonomy, sensor fusion, and robot perception and am looking to deepen my understanding of these concepts.
  <br><br>
  <a href="https://www.linkedin.com/in/benjamin-adams-401259267">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-4LF9VYC5YR # your Google Analytics tracking ID here
